version: "2"
services:
  server:
    build: .
    ports:
      # external:internal
      - "80:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=/var/www/project/server.py
    volumes:
      - ./project:/var/www/project
